### ISSUE TITLE
Suggestion: Make .java and .py files not fatal

### ISSUE THREAD

**Issue by cajoho99** [SonarSource/sonarcloud-github-c-cpp#34]
I suggest that when  encountering a .java file during a scan on a repository it should ignore that file, print a warning and continue.
Currently it is a fatal error that blocks the run from proceeding.

**Comment by cajoho99** [comment]
Probably more of an issue with sonar-scanner than this action

**Comment by ericg138** [comment]
Hi @cajoho99,
Sorry for not getting back to you sooner.
Indeed this is more an issue with the scanner rather than this action.
We will soon close the GitHub Issues section on this repo. If you still encounter this error, feel free to open a thread on the [community forum](https://community.sonarsource.com/).
