### ISSUE TITLE
support for split workflows

### ISSUE THREAD

**Issue by BenWibking** [SonarSource/sonarcloud-github-c-cpp#37]
Hi,

Is it possible to run the build wrapper and code scanner steps in separate workflows, where the second workflow is triggered by the build workflow? This is done by other code analysis actions, e.g. https://github.com/ZedThree/clang-tidy-review#usage-in-fork-environments-split-workflow.

This is necessary for our repository in order to support PRs from external forks.

**Comment by 7PH** [comment]
Hello @BenWibking , 

Sorry fo the late resopnse. As of today, we don't offer this possibility out of the box. From what I see, the upload action they have:
- Upload artifacts using a GH-maintained action [here](https://github.com/ZedThree/clang-tidy-review/blob/master/upload/action.yml#L10).
- Download using Python [here](https://github.com/ZedThree/clang-tidy-review/blob/85799d63d217e8d0686b7735fb923acc986d8043/post/clang_tidy_review/clang_tidy_review/__init__.py#L910)

So, it is possible to implement this in your pipeline by uploading/downloading artifacts manually. Have you looked into these?
- [actions/upload-artifact](https://github.com/actions/upload-artifact)
- [actions/download-artifact](https://github.com/actions/download-artifact)
- [action-download-artifact](https://github.com/dawidd6/action-download-artifact)

I'll also raise this with the team and we can decide if that's a scenario we want to support out of the box,

Hope this helps

**Comment by BenWibking** [comment]
> Hi @BenWibking, and thanks for sharing your question,
> 
> > Is it possible to run the build wrapper and code scanner steps in separate workflows,
> 
> When using the CFamily analyzer, we recommend running the scanner on the same machine where the build took place. The reason is that the analyzer needs to access information from the build toolchain or headers that are possibly installed as system libraries during the analysis. See the official docs [here](https://docs.sonarsource.com/sonarcloud/advanced-setup/languages/c-c-objective-c/#important-notes). Basically, this is the easiest way to ensure that the information collected by [build-wrapper](https://sonarsource.atlassian.net/browse/BUILD-wrapper) are still applicable in the environment where the scanner is running.
> 
> > This is necessary for our repository in order to support PRs from external forks.
> 
> If I understand correctly, the concern here is exposing the SonarCloud token when analyzing untrusted code from external forks. Unfortunately, we don't have a solution for that yet, but we have [a card on our product board](https://portal.productboard.com/sonarsource/1-sonarcloud/c/50-sonarcloud-analyzes-external-pull-request), please feel free to vote for the feature and leave a comment there.

Yes, that's exactly the reason. Thanks, I've voted for the feature.
> 
> The good news, however, is that analyzing PRs from forked repositories can still be done when [using Automatic Analysis](https://docs.sonarsource.com/sonarcloud/advanced-setup/automatic-analysis/). This is secure because the analysis is run entirely on the cloud (nothing is required to run on your CI, and therefore there is no risk of leaking tokens). Check the prerequisites section in the docs to see if this is a possible solution for your project.

I looked at the documentation for this, but since we generate header files during the build process, I don't think this will work for us.

**Comment by michael-jabbour-sonarsource** [comment]
Hi @BenWibking,

Thank you for sharing your vote on the product board.

> but since we generate header files during the build process, I don't think this will work for us.

If your build heavily relies on these generated headers, then they may have an impact on the analysis. You can try to set Automatic Analysis up temporarily and you will get a warning on the UI if the Automatic Analysis is not recommended for your project.

Another non-ideal option that I could think of, is to check-in the generated headers for your project, so that they are available for the analyzer when running in Automatic Analysis mode...

If you have further questions about Automatic Analysis for C and C++, I would suggest that you create a topic on [our community forum](https://community.sonarsource.com/) with the tag "cfamily". The topic will be seen by people who developed the Automatic Analysis feature, and they may be able to provide better suggestions.

We are going to remove the issues tab from this repository soon, so I am closing this issue...
